# Generated by Django 4.2 on 2025-01-03 14:41

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='enter your title here: ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='describe here detail info about the original')),
                ('catagory', models.CharField(choices=[('original', 'Original'), ('order', 'Order')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='originals.artwork')),
            ],
        ),
    ]
